# Generated by Django 4.1.4 on 2022-12-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("site_library", "0002_pdfloader"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name="Book",
            new_name="Cafe",
        ),
        migrations.DeleteModel(
            name="Library",
        ),
        migrations.RenameField(
            model_name="cafe",
            old_name="author",
            new_name="address",
        ),
    ]
